[package]
name = "neba"
version.workspace = true
edition.workspace = true

[[bin]]
name = "neba"
path = "src/main.rs"

[dependencies]
neba_lexer       = { path = "../neba_lexer" }
neba_parser      = { path = "../neba_parser" }
neba_interpreter = { path = "../neba_interpreter" }
